version: '1'
services:
  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/data
  solr:
    image: solr:slim
    container_name: solr
    ports:
      - "8983:8983"
    volumes:
      - ./solr-data:/var/solr
      - ./security.json:/var/solr/data/security.json
    environment:
      - SOLR_HOME=/var/solr/data
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
    restart: unless-stopped
  be:
    image: shegga/phung_be:jenkins
    container_name: phung_be
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - DATABASE_HOST=phung-vip-db.cxoa0mia8nkk.ap-southeast-1.rds.amazonaws.com
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=iMbFfqQvBEc2i0gxAqn8
      - DATABASE_PORT=3306
      - ALLOWED_ORIGINS=https://phungvipfrontend.vercel.app
      - BASE_URL=https://phungvip.io.vn
      - PROXY_HOST=103.156.91.191
      - PROXY_PORT=2021
      - PROXY_USER=ipzn6e1o
      - PROXY_PASS=iPZN6e1O
      - COOKIE_DOMAIN: phungvip.io.vn
      - SOLR_URL=http://localhost:8983/solr
    networks:
      - app_net
  caddy:
    image: caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "8080:8080"
      - "443:443"
      - "80:80"
    restart: unless-stopped
volumes:
  redis_data:
networks:
  app_net:
    driver: bridge
